name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate Unity License
        uses: game-ci/unity-activate@v3
        with:
          unityVersion: 2022.3.0f1
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Unity Editor
        uses: game-ci/unity-setup@v3
        with:
          unityVersion: 2022.3.0f1

      - name: Build Windows Standalone
        uses: game-ci/unity-builder@v3
        with:
          projectPath: .
          targetPlatform: StandaloneWindows64
          buildMethod: BuildScript.PerformWindowsBuild
          outputPath: Build/windows/MyGame.exe

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: Build/windows/MyGame.exe
